=== ElderNoSpace/Deep-Space-Magic/xml/xml.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--The hypertarget of action is Action_<name>-->
    <!--The hypertarget of item is Item_<name>-->
    <!--The hypertarget of weapon is Weapon_<name>-->
    <!--The hypertarget of armour is Armour_<name>-->
    <!--The hypertarget of activity is Activity_<name>-->

    <!--The root element of a root xml file-->
    <xs:element name="section" type="sectionType"/>

    <!--The root element of a list of actions-->
    <xs:element name="actions" type="actionsType"/>

    <!--The rool element of a list of downtime activities-->
    <xs:element name="downtime" type="downtimeType"/>

    <!--The root element of a list of equipment-->
    <xs:element name="equipment" abstract="true"/>
    <xs:element name="items" type="itemsType" substitutionGroup="equipment"/>
    <xs:element name="weapons" type="weaponsType" substitutionGroup="equipment"/>
    <xs:element name="armours" type="armoursType" substitutionGroup="equipment"/>

    <!--The root element of a list of classes-->
    <xs:element name="classes" type="classesType"/>

    <!--Things that go in a section of the latex document-->
    <xs:complexType name="sectionType">
         <xs:sequence>
            <xs:element name="category" type="categoryType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!--Common preamble elements to both categoryType and subcategoryType-->
    <xs:group name="categoryGroup">
        <xs:sequence>
            <xs:element name="index" type="xs:string" minOccurs="0" />
            <xs:element name="name" type="xs:string" />
            <xs:element name="filename" type="xs:anyURI" minOccurs="0" />
            <xs:element name="description" type="xs:string" minOccurs="0" />
        </xs:sequence>
    </xs:group>

    <!--The meat of a category-->
    <xs:group name="categoryContentsGroup">
        <xs:sequence>
            <xs:element name="subdoc" type="refedType" minOccurs="0" maxOccurs="unbounded"/><!--Reference another xml document-->
            <xs:element name="reftex" type="refedType" minOccurs="0" maxOccurs="unbounded"/><!--\import another tex document in the output-->
            <xs:element name="things" type="thingType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:group>

    <!--A category of things that go into a subsection-->
    <xs:complexType name="categoryType">
        <xs:sequence>
            <xs:group ref="categoryGroup" />
            <xs:choice>
                <xs:group ref="categoryContentsGroup"/>
                <xs:sequence>
                    <xs:element name="subcategory" type="subCategoryType" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <!--A subcategory that go into a subsubsection-->
    <xs:complexType name="subCategoryType">
        <xs:sequence>
            <xs:group ref="categoryGroup" />
            <xs:group ref="categoryContentsGroup"/>
        </xs:sequence>
    </xs:complexType>

    <!--A reference to another file-->
    <xs:complexType name="refedType">
        <xs:attribute name="ref" type="xs:anyURI" use="required"/>
    </xs:complexType>

    <!--A list of things that can be in a category or subcategory-->
    <xs:complexType name="thingType">
        <xs:all>
            <xs:element ref="actions" minOccurs="0"/>
            <xs:element ref="downtime" minOccurs="0"/>
            <xs:element ref="equipment" minOccurs="0"/>
            <xs:element ref="classes" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <!--A list of actions-->
    <xs:complexType name="actionsType">
        <xs:sequence>
            <xs:element name="action" type="actionType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!--Something a character can do-->
    <xs:complexType name="actionType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:group ref="typeGroup"/>
            <xs:element name="time" type="xs:string" minOccurs="0"/>
            <xs:element name="cost" type="xs:string" minOccurs="0"/>
            <xs:element name="effect" type="xs:string"/>
            <xs:element name="upeffect" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="difficulty" type="xs:string"/>
        <xs:attribute name="upgrade" type="xs:string"/>
        <xs:attribute name="specialist" default="false" type="xs:boolean"/>
        <xs:attributeGroup ref="indexGroup"/>
    </xs:complexType>

    <!--A list of classes-->
    <xs:complexType name="classesType">
        <xs:sequence>
            <xs:element name="class" type="classType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!--A class-->
    <xs:complexType name="classType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:group ref="typeGroup"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="level" type="levelType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="indexGroup"/>
    </xs:complexType>

    <!--When the requirement is met the charater gains the benifit-->
    <xs:complexType name="levelType">
        <xs:sequence>
            <xs:element name="requiredAction" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="benifit" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!-- A list of downtime activites-->
    <xs:complexType name="downtimeType">
        <xs:sequence>
            <xs:element name="activity" type="activityType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!--A downtime activity-->
    <xs:complexType name="activityType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:group ref="typeGroup"/>
            <xs:element name="score" type="xs:int"/>
            <xs:element name="effect" type="xs:string"/>
            <xs:element ref="actions"/>
        </xs:sequence>
        <xs:attributeGroup ref="indexGroup"/>
    </xs:complexType>

    <!--Common elements to all equipment-->
    <xs:group name="equipmentGroup">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:group ref="typeGroup"/>
            <xs:element name="cost" type="xs:string"/>
            <xs:element ref="actions" minOccurs="0"/>
            <xs:element name="passiveEffect" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:group>

    <!--A list of items-->
    <xs:complexType name="itemsType">
        <xs:sequence>
            <xs:element name="item" type="itemType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="indexGroup"/>
    </xs:complexType>

    <!--A basic type of equipment-->
    <xs:complexType name="itemType">
        <xs:group ref="equipmentGroup"/>
    </xs:complexType>

    <!--A list of weapons-->
    <xs:complexType name="weaponsType">
        <xs:sequence>
            <xs:element name="weapon" type="weaponType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="indexGroup"/>
    </xs:complexType>

    <!--Equipment that can be used to attack with-->
    <xs:complexType name="weaponType">
        <xs:sequence>
            <xs:group ref="equipmentGroup"/>
            <xs:element name="difficulty" type="xs:string"/>
            <xs:element name="time" type="xs:string"/>
            <xs:element name="range" type="xs:string"/>
            <xs:element name="aoe" type="xs:string" minOccurs="0"/>
            <xs:element name="damage" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <!--A list of armour-->
    <xs:complexType name="armoursType">
        <xs:sequence>
            <xs:element name="armour" type="armourType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="indexGroup"/>
    </xs:complexType>

    <!--Equipment that protects a character-->
    <xs:complexType name="armourType">
        <xs:sequence>
            <xs:group ref="equipmentGroup"/>
            <xs:element name="save" type="attributeEnum"/>
            <xs:element name="modifier" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:group name="typeGroup">
        <xs:sequence>
            <xs:element name="type" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:group>

    <xs:simpleType name="attributeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Physical"/>
            <xs:enumeration value="Mental"/>
            <xs:enumeration value="Spirit"/>
        </xs:restriction>
    </xs:simpleType>

    <!--If yes the thing is put in the index-->
    <xs:attributeGroup name="indexGroup">
        <xs:attribute name="index" default="false" type="xs:boolean"/>
    </xs:attributeGroup>
</xs:schema>

=== ElderNoSpace/Deep-Space-Magic/xml/Equipment/Equipment.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "../Converter.xsl"?>
<section xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml.xsd">
    <category>
        <index>Weaponry</index>
        <name>Weaponry</name>
        <subcategory>
            <index>Ranged Weapons</index>
            <name>Ranged Weapons</name>
            <subdoc ref="RangedWeapons.xml"/>
        </subcategory>
        <subcategory>
            <index>Grenades</index>
            <name>Grenades</name>
            <subdoc ref="Grenades.xml"/>
        </subcategory>
        <subcategory>
            <index>Melee Weapons</index>
            <name>Melee Weapons</name>
            <subdoc ref="MeleeWeapons.xml"/>
        </subcategory>
    </category>
    <category>
        <index>Armour</index>
        <name>Armour</name>
        <subdoc ref="Armour.xml"/>
    </category>
    <category>
        <index>Vehicles</index>
        <name>Vehicles</name>
        <description>
            Vehicles are treated as a Character but need other Non-Vehicle Characters to use their Actions to pilot, gun, repair, ect. the Vehicle.
        </description>
    </category>
</section>

=== ElderNoSpace/Deep-Space-Magic/xml/Actions/Alchemy.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "../Converter.xsl"?> 
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml.xsd">
    <action upgrade="$l$" difficulty="15" specialist="true">
        <name>Kinetic Shot</name>
        <type>Alchemy, Kinetic, Mental</type>
        <time>20</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>Target Character within 100m must make a Physical Save or be pushed back 15m and take 1 damage.</effect>
        <upeffect>The Difficulty Count is at -1 per level and the distance pushed back increases by 1 per level.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="15" specialist="true">
        <name>Kinetic Blast</name>
        <type>Alchemy, Kinetic, Mental</type>
        <time>20</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>All Characters in a 45$^{\circ}$ cone 50m must make a Physical Save or take 1 damage.</effect>
        <upeffect>Difficulty Count is at -1 per level and at level 5 the arc increases to 60$^{\circ}$.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="10" specialist="true">
        <name>Forceful Blade</name>
        <type>Alchemy, Kinetic, Mental, Melee</type>
        <time>10</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>For the next 50 Time Units when your Character hits with a Melee Weapon Attack the Target Character suffers a -1 to the Saving Throw</effect>
        <upeffect>Difficulty Count is at -1 per level, the duration increases by 50 Time Units per level and the modifier is decreased by 1 per level.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="15" specialist="true">
        <name>Forceful Shot</name>
        <type>Alchemy, Kinetic, Ranged, Mental</type>
        <time>10</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>For the next 50 Time Units when your Character hits with a Ranged Weapon Attack using a Ballistic or Rail weapon the Target Character suffers a -1 to the Saving Throw</effect>
        <upeffect>Difficulty Count is at -1 per level, the duration increases by 50 Time Units per level and the modifier is decreased by 1 per 2 levels.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="10" specialist="true">
        <name>Kinetic Jump</name>
        <type>Alchemy, Kinetic, Movement, Mental</type>
        <time>30</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>Jump over things from a minimum of 50m to a maximum of 100m.</effect>
        <upeffect>Difficulty Count is at -1 per level, the Time Cost is at -1 per level and the maximum distance increases at 10m per level</upeffect>
    </action>
    <action upgrade="$l$" difficulty="15" specialist="true">
        <name>Light Shot</name>
        <type>Alchemy, Light, Mental</type>
        <time>20</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>Target Character within 200m must make a Physical Save or take 1 damage.</effect>
        <upeffect>The Difficulty Count is at -1 per level and range is at +5 per level.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="20" specialist="true">
        <name>Light Blast</name>
        <type>Alchemy, Light, Mental</type>
        <time>20</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>All Characters in a 75m line must make a Physical Save or take 1 damage.</effect>
        <upeffect>Difficulty Count is at -1 per level and range is at +5 per level.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="10" specialist="true">
        <name>Blinding Light</name>
        <type>Alchemy, Light, Mental</type>
        <time>15</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>Target Character within 150m must make a Mental Saving Throw or suffer a -5 to all Difficulty Count Rolls for the next 100 Time Units</effect>
        <upeffect>Difficulty Count is at -1 per level and duration is increased by 10 Time Units.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="15" specialist="true">
        <name>Eletric Shot</name>
        <type>Alchemy, Eletric, Mental</type>
        <time>20</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>Target Character within 100m must make a Physical Save or have to wait 5 Time Units and take 1 damage.</effect>
        <upeffect>The Difficulty Count is at -1 per level and Time Units waited increases by +1 per level.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="20" specialist="true">
        <name>Eletric Arc</name>
        <type>Alchemy, Eletric, Mental</type>
        <time>20</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>Target Character within 75m must make a Physical Save or take 1 damage. Each time a Character takes damage from this Action the nearest Character that has not been effected by it must make a Physical Save or take 1 damage</effect>
        <upeffect>Difficulty Count is at -1 per level.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="10" specialist="true">
        <name>Rail Shot</name>
        <type>Alchemy, Eletric, Ranged, Mental</type>
        <time>+5</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>Modifies Shoot Ranged Weapon Action Range by +25m of a Ballistic Weapon.</effect>
        <upeffect>-1 per level to the Time Modifier up to five levels and increases range by 5m per level.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="10" specialist="true">
        <name>Lightning Throwing</name>
        <type>Alchemy, Eletric, Ranged, Mental</type>
        <time>5</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>For 50 Time Units a spear of lightning Appears in your Character's hand which has Difficulty Count 15, Time 10, Range 100, Damage 1.</effect>
        <upeffect>Difficult Count of this Action is at -1 per level, the duration increases by 50 Time Units and the range of the spear of lightning is at +10m per level.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="15" specialist="true">
        <name>Fire Shot</name>
        <type>Alchemy, Fire, Mental</type>
        <time>20</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>Target Character within 50m must make a Physical Save or take 2 damage.</effect>
        <upeffect>The Difficulty Count is at -1 per level and every 5 levels damage increases by 1.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="15" specialist="true">
        <name>Fire Blast</name>
        <type>Alchemy, Fire, Mental</type>
        <time>20</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>All Characters in a 10m radius circle at 75m must make a Physical Save or take 1 damage.</effect>
        <upeffect>Difficulty Count is at -1 per level and radius is at +1m per level.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="15" specialist="true">
        <name>Flame Grenade</name>
        <type>Alchemy, Fire, Mental</type>
        <time>20</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>All Characters in a 5m radius circle at 50m must make a Physical Save or take 1 damage, ignores Cover.</effect>
        <upeffect>Difficulty Count is at -1 per level and radius is at +1m per level.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="10" specialist="true">
        <name>Flame Blade</name>
        <type>Alchemy, Fire, Melee, Mental</type>
        <time>5</time>
        <cost>1 point from the Mental Pool</cost>
        <effect>For 50 Time Units a blade of fire Appears in your Character's hand which has Difficulty Count 15, Time 15, Range 1, Damage 2 and is always a Melee Weapon.</effect>
        <upeffect>Difficult Count of this Action is at -1 per level, the duration increases by 50 Time Units and the range of the blade of fire is at +1m per level.</upeffect>
    </action>
</actions>

=== ElderNoSpace/Deep-Space-Magic/xml/Actions/Actions.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "../Converter.xsl"?>
<section xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml.xsd">
    <category>
        <index>Generic Actions</index>
        <name>Generic</name>
        <subcategory>
            <name>Movement</name>
            <subdoc ref="Movement.xml" />
        </subcategory>
        <subcategory>
            <name>Equipment</name>
            <subdoc ref="Equipment.xml" />
        </subcategory>
    </category>
    <category>
        <index>Combat Actions</index>
        <name>Combat</name>
        <subcategory>
            <name>Ranged Weaponry</name>
            <subdoc ref="RangedWeaponry.xml" />
        </subcategory>
        <subcategory>
            <name>Alchemy</name>
            <subdoc ref="Alchemy.xml" />
        </subcategory>
        <subcategory>
            <name>Psychic</name>
            <subdoc ref="Psychic.xml" />
        </subcategory>
        <subcategory>
            <name>Technomancy</name>
            <subdoc ref="Technomancy.xml" />
        </subcategory>
        <subcategory>
            <name>Thaumaturgy</name>
            <subdoc ref="Thaumaturgy.xml" />
        </subcategory>
        <!--%Thaumaturgy
            %Red Crystals -Evil and always a hidden cost-->
    </category>
    <category>
        <index>Social Actions</index>
        <name>Social</name>
    </category>
    <category>
        <index>Investigation Actions</index>
        <name>Investigation</name>
    </category>
    <category>
        <index>Downtime Actions</index>
        <name>Downtime</name>
        <description>
            Each Downtime Action has an associated Downtime Activity. The effect listed is for the completion of the Downtime Activity, a successful Downtime Action will increase the Success Score of the associated Downtime Activity by 1.

            Downtime Actions have the total Success Score needed for the completion of the associated Downtime Activity at the bottom of the Action.
        </description>
        <subcategory>
            <name>Crafting</name>
            <reftex ref="../temp/Actions/Weapons.tex"/>
        </subcategory>
        <subcategory>
            <name>Gambling</name>
            <reftex ref="../temp/Actions/Gambling.tex"/>
        </subcategory>
    </category>
    <!--<category>
        <index>Equipment Actions</index>
        <name>Equipment</name>
        <subcategory>
            <index>Ranged Weapon Action</index>
            <name>Ranged Weapon</name>
            <reftex ref="../temp/Actions/RangedWeapons.tex"/>
        </subcategory>
    </category>-->
</section>

=== ElderNoSpace/Deep-Space-Magic/xml/DowntimeActivities/Crafting.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-sylesheet type="text/xsl" href="../Converter.xsl"?>
<downtime xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml.xsd">
    <activity>
        <name>Create Simple Melee Weapon</name>
        <type>Crafting</type>
        <score>3</score>
        <effect>Creates a Simple Melee Weapon.</effect>
        <actions>
            <action difficulty="15" upgrade="$l$" specialist="true">
                <name>Create Melee Weapon</name>
                <type>Crafting</type>
                <cost>One half the total market value of the weapon to be crafted is needed.</cost>
                <effect>
                    +1 Success Score
                </effect>
                <upeffect>The difficulty count is at -1 per level.</upeffect>
            </action>
        </actions>
    </activity>
</downtime>

=== ElderNoSpace/Deep-Space-Magic/xml/Actions/Equipment.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "../Converter.xsl"?> 
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml.xsd">
    <action difficulty="0">
        <name>Equip Weapon</name>
        <type>Misc</type>
        <time>10</time>
        <effect>Your Character equips a Weapon, if the Weapon is One Handed another One Handed Weapon can be equip aswell.</effect>
    </action>
    <action difficulty="0">
        <name>Unequip Weapon</name>
        <type>Misc</type>
        <time>10</time>
        <effect>Your Character unequips a Weapon, if the Weapon is One Handed another One Handed Weapon can be unequip aswell.</effect>
    </action>
</actions>

=== ElderNoSpace/Deep-Space-Magic/xml/DowntimeActivities/Gambling.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-sylesheet type="text/xsl" href="../Converter.xsl"?>
<downtime xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml.xsd">
    <activity>
        <name>Gamble</name>
        <type>Luck</type>
        <score>1</score>
        <effect>The amount of gold spent in the cost times 1.5 is gained.</effect>
        <actions>
            <action difficulty="10" upgrade="$l^2$">
                <name>Gamble</name>
                <type>Luck</type>
                <cost>
                    Any amount of gold.
                </cost>
                <effect>
                    +1 Success Score
                </effect>
                <upeffect>The difficulty count is at -1 per level.</upeffect>
            </action>
        </actions>
    </activity>
</downtime>

=== ElderNoSpace/Deep-Space-Magic/xml/Equipment/MeleeWeapons.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "../Converter.xsl"?>
<weapons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml.xsd">
    <weapon>
        <name>Metal Sword</name>
        <type>Sword, Melee, Simple</type>
        <cost>25</cost>
        <difficulty>15</difficulty>
        <time>20</time>
        <range>1</range>
        <damage>1</damage>
    </weapon>
    <weapon>
        <name>Heat Sword</name>
        <type>Heat, Sword, Melee</type>
        <cost>50</cost>
        <difficulty>20</difficulty>
        <time>20</time>
        <range>1</range>
        <damage>2</damage>
    </weapon>
    <weapon>
        <name>Heat Axe</name>
        <type>Heat, Axe, Melee</type>
        <cost>75</cost>
        <difficulty>15</difficulty>
        <time>35</time>
        <range>1</range>
        <damage>2</damage>
    </weapon>
    <weapon>
        <name>Long Beam Sword</name>
        <type>Beam, Sword, Melee</type>
        <cost>50</cost>
        <difficulty>13</difficulty>
        <time>20</time>
        <range>1</range>
        <damage>1</damage>
    </weapon>
    <weapon>
        <name>Short Beam Sword</name>
        <type>Beam, Sword, Melee</type>
        <cost>50</cost>
        <difficulty>15</difficulty>
        <time>15</time>
        <range>1</range>
        <damage>1</damage>
    </weapon>
    <weapon>
        <name>Force Sword</name>
        <type>Force, Sword, Melee</type>
        <cost>75</cost>
        <passiveEffect>Push the enemy 1d6 meters on hit, before Saving Throw.</passiveEffect>
        <difficulty>15</difficulty>
        <time>20</time>
        <range>1</range>
        <damage>1</damage>
    </weapon>
</weapons>

=== ElderNoSpace/Deep-Space-Magic/xml/DowntimeActivities/DowntimeActivities.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../Converter.xsl"?>
<section xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml.xsd">
    <category>
        <index>Crafting</index>
        <name>Crafting</name>
        <subcategory>
            <name>Weapons</name>
            <subdoc ref="Crafting.xml"/>
        </subcategory>
    </category>
    <category>
        <index>Gambling</index>
        <name>Gambling</name>
        <subdoc ref="Gambling.xml"/>
    </category>
</section>
