=== ElderNoSpace/Deep-Space-Magic/xml/xml.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--The hypertarget of action is Action_<name>-->
    <!--The hypertarget of item is Item_<name>-->
    <!--The hypertarget of weapon is Weapon_<name>-->
    <!--The hypertarget of armour is Armour_<name>-->
    <!--The hypertarget of activity is Activity_<name>-->

    <!--The root element of a root xml file-->
    <xs:element name="section" type="sectionType"/>

    <!--The root element of a list of actions-->
    <xs:element name="actions" type="actionsType"/>

    <!--The rool element of a list of downtime activities-->
    <xs:element name="downtime" type="downtimeType"/>

    <!--The root element of a list of equipment-->
    <xs:element name="equipment" abstract="true"/>
    <xs:element name="items" type="itemsType" substitutionGroup="equipment"/>
    <xs:element name="weapons" type="weaponsType" substitutionGroup="equipment"/>
    <xs:element name="armours" type="armoursType" substitutionGroup="equipment"/>

    <!--The root element of a list of classes-->
    <xs:element name="classes" type="classesType"/>

    <!--Things that go in a section of the latex document-->
    <xs:complexType name="sectionType">
         <xs:sequence>
            <xs:element name="category" type="categoryType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!--Common preamble elements to both categoryType and subcategoryType-->
    <xs:group name="categoryGroup">
        <xs:sequence>
            <xs:element name="index" type="xs:string" minOccurs="0" />
            <xs:element name="name" type="xs:string" />
            <xs:element name="filename" type="xs:anyURI" minOccurs="0" />
            <xs:element name="description" type="xs:string" minOccurs="0" />
        </xs:sequence>
    </xs:group>

    <!--The meat of a category-->
    <xs:group name="categoryContentsGroup">
        <xs:sequence>
            <xs:element name="subdoc" type="refedType" minOccurs="0" maxOccurs="unbounded"/><!--Reference another xml document-->
            <xs:element name="reftex" type="refedType" minOccurs="0" maxOccurs="unbounded"/><!--\import another tex document in the output-->
            <xs:element name="things" type="thingType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:group>

    <!--A category of things that go into a subsection-->
    <xs:complexType name="categoryType">
        <xs:sequence>
            <xs:group ref="categoryGroup" />
            <xs:choice>
                <xs:group ref="categoryContentsGroup"/>
                <xs:sequence>
                    <xs:element name="subcategory" type="subCategoryType" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <!--A subcategory that go into a subsubsection-->
    <xs:complexType name="subCategoryType">
        <xs:sequence>
            <xs:group ref="categoryGroup" />
            <xs:group ref="categoryContentsGroup"/>
        </xs:sequence>
    </xs:complexType>

    <!--A reference to another file-->
    <xs:complexType name="refedType">
        <xs:attribute name="ref" type="xs:anyURI" use="required"/>
    </xs:complexType>

    <!--A list of things that can be in a category or subcategory-->
    <xs:complexType name="thingType">
        <xs:all>
            <xs:element ref="actions" minOccurs="0"/>
            <xs:element ref="downtime" minOccurs="0"/>
            <xs:element ref="equipment" minOccurs="0"/>
            <xs:element ref="classes" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <!--A list of actions-->
    <xs:complexType name="actionsType">
        <xs:sequence>
            <xs:element name="action" type="actionType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!--Something a character can do-->
    <xs:complexType name="actionType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:group ref="typeGroup"/>
            <xs:element name="time" type="xs:string" minOccurs="0"/>
            <xs:element name="cost" type="xs:string" minOccurs="0"/>
            <xs:element name="effect" type="xs:string"/>
            <xs:element name="upeffect" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="difficulty" type="xs:string"/>
        <xs:attribute name="upgrade" type="xs:string"/>
        <xs:attribute name="specialist" default="false" type="xs:boolean"/>
        <xs:attributeGroup ref="indexGroup"/>
    </xs:complexType>

    <!--A list of classes-->
    <xs:complexType name="classesType">
        <xs:sequence>
            <xs:element name="class" type="classType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!--A class-->
    <xs:complexType name="classType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:group ref="typeGroup"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="level" type="levelType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="indexGroup"/>
    </xs:complexType>

    <!--When the requirement is met the charater gains the benifit-->
    <xs:complexType name="levelType">
        <xs:sequence>
            <xs:element name="requiredAction" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="benifit" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!-- A list of downtime activites-->
    <xs:complexType name="downtimeType">
        <xs:sequence>
            <xs:element name="activity" type="activityType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!--A downtime activity-->
    <xs:complexType name="activityType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:group ref="typeGroup"/>
            <xs:element name="score" type="xs:int"/>
            <xs:element name="effect" type="xs:string"/>
            <xs:element ref="actions"/>
        </xs:sequence>
        <xs:attributeGroup ref="indexGroup"/>
    </xs:complexType>

    <!--Common elements to all equipment-->
    <xs:group name="equipmentGroup">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:group ref="typeGroup"/>
            <xs:element name="cost" type="xs:string"/>
            <xs:element ref="actions" minOccurs="0"/>
            <xs:element name="passiveEffect" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:group>

    <!--A list of items-->
    <xs:complexType name="itemsType">
        <xs:sequence>
            <xs:element name="item" type="itemType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="indexGroup"/>
    </xs:complexType>

    <!--A basic type of equipment-->
    <xs:complexType name="itemType">
        <xs:group ref="equipmentGroup"/>
    </xs:complexType>

    <!--A list of weapons-->
    <xs:complexType name="weaponsType">
        <xs:sequence>
            <xs:element name="weapon" type="weaponType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="indexGroup"/>
    </xs:complexType>

    <!--Equipment that can be used to attack with-->
    <xs:complexType name="weaponType">
        <xs:sequence>
            <xs:group ref="equipmentGroup"/>
            <xs:element name="difficulty" type="xs:string"/>
            <xs:element name="time" type="xs:string"/>
            <xs:element name="range" type="xs:string"/>
            <xs:element name="aoe" type="xs:string" minOccurs="0"/>
            <xs:element name="damage" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <!--A list of armour-->
    <xs:complexType name="armoursType">
        <xs:sequence>
            <xs:element name="armour" type="armourType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="indexGroup"/>
    </xs:complexType>

    <!--Equipment that protects a character-->
    <xs:complexType name="armourType">
        <xs:sequence>
            <xs:group ref="equipmentGroup"/>
            <xs:element name="save" type="attributeEnum"/>
            <xs:element name="modifier" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:group name="typeGroup">
        <xs:sequence>
            <xs:element name="type" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:group>

    <xs:simpleType name="attributeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Physical"/>
            <xs:enumeration value="Mental"/>
            <xs:enumeration value="Spirit"/>
        </xs:restriction>
    </xs:simpleType>

    <!--If yes the thing is put in the index-->
    <xs:attributeGroup name="indexGroup">
        <xs:attribute name="index" default="false" type="xs:boolean"/>
    </xs:attributeGroup>
</xs:schema>

=== ElderNoSpace/Deep-Space-Magic/xml/Equipment/Armour.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "../Converter.xsl"?> 
<armours xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml.xsd">
    <armour>
        <name>Ballistic Jacket</name>
        <type>Light Armour</type>
        <type>Physical Armour</type>
        <type>Armour</type>
        <cost>150</cost>
        <save>Physical</save>
        <modifier>1</modifier>
    </armour>
    <armour>
        <name>Plated Chestpeice</name>
        <type>Medium Armour</type>
        <type>Physical Armour</type>
        <type>Armour</type>
        <cost>200</cost>
        <passiveEffect>
            <speedIncrease>-0.1</speedIncrease>
            <!---0.1m/s speed-->
        </passiveEffect>
        <save>Physical</save>
        <modifier>2</modifier>
    </armour>
    <armour>
        <name>Full Cover Plating</name>
        <type>Heavy Armour</type>
        <type>Physical Armour</type>
        <type>Armour</type>
        <cost>500</cost>
        <passiveEffect>
            <speedIncrease>-0.5</speedIncrease>
        </passiveEffect>
        <save>Physical</save>
        <modifier>3</modifier>
    </armour>
</armours>

=== ElderNoSpace/Deep-Space-Magic/xml/Actions/RangedWeaponry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "../Converter.xsl"?> 
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml.xsd">
    <action upgrade="$l$" difficulty="Weapon Difficulty">
        <name>Shoot Ranged Weapon</name>
        <type>Shoot</type>
        <type>Ranged</type>
        <time>Weapon Time</time>
        <cost>1 ammunition that the Shoot Weapon uses.</cost>
        <effect>Target Character at Weapon Range and all other Characters within area of effect must make a Physical Save or take Weapon Damage.</effect>
        <upeffect>The Difficulty Count is at -1 per level.</upeffect>
    </action>
    <action upgrade="$l^2$">
        <name>Shoot Two Ranged Weapons</name>
        <type>Shoot</type>
        <type>Ranged</type>
        <time>Sum of both Weapon Times</time>
        <effect>Make a Shoot Ranged Weapon Action for two differenent equiped Ranged Weapons immediatly.</effect>
        <upeffect>The Action Time reduces by 1 each level to a minimum of the longest of the two Weapon's Time.</upeffect>
    </action>
    <action upgrade="$l$">
        <name>Throw Grenade</name>
        <type>Throw</type>
        <type>Ranged</type>
        <time>Weapon Time</time>
        <cost>1 of the weapon used</cost>
        <effect>Target Character at Weapon Range and all other Characters within Area of Effect must make a Physical Save or take Weapon Damage.</effect>
        <upeffect>The Difficulty Count is at -1 per level.</upeffect>
    </action>
    <action upgrade="$l!$">
        <name>Aim</name>
        <type>Shoot</type>
        <type>Ranged</type>
        <time>+5</time>
        <effect>Modifies Shoot Ranged Weapon Action Difficulty by -3.</effect>
        <upeffect>-1 per level to the Time Modifier up to five levels.</upeffect>
    </action>
    <action upgrade="$l$">
        <name>Double Shot</name>
        <type>Shoot</type>
        <type>Ranged</type>
        <type>Physical</type>
        <time>Weapon Time</time>
        <cost>1 point from the Physical Pool</cost>
        <effect>Make two Shoot Ranged Weapon Actions with a Rapid Fire Ranged Weapon at +5 Difficulty</effect>
        <upeffect>Extra difficulty is decreased by 1 each level to a minimum of 0 and every 5 levels the number of Shoot Ranged Weapon Actions made increases by 1.</upeffect>
    </action>
</actions>

=== ElderNoSpace/Deep-Space-Magic/xml/Equipment/Grenades.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "../Converter.xsl"?>
<weapons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml.xsd">
    <weapon>
        <name>Frag Grenade</name>
        <type>Grenade</type>
        <type>Throw</type>
        <type>Ballistic</type>
        <type>Ranged</type>
        <cost>5</cost>
        <passiveEffect><ignoresCover/></passiveEffect>
        <difficulty>15</difficulty>
        <time>15</time>
        <range>50</range>
        <damage>1</damage>
    </weapon>
    <weapon>
        <name>Plasma Grenade</name>
        <type>Grenade</type>
        <type>Throw</type>
        <type>Plasma</type>
        <type>Ranged</type>
        <cost>10</cost>
        <passiveEffect><ignoresCover/></passiveEffect>
        <difficulty>15</difficulty>
        <time>15</time>
        <range>50</range>
        <aoe><circle>10</circle></aoe>
        <damage>1</damage>
    </weapon>
    <weapon>
        <name>Force Grenade</name>
        <type>Force</type>
        <type>Grenade</type>
        <type>Throw</type>
        <type>Ranged</type>
        <cost>5</cost>
        <passiveEffect>
            <ignoresCover/>
            <push>5</push>
            <!--Ignores Cover, pushes target on hit 5m in any direction-->
        </passiveEffect>
        <difficulty>15</difficulty>
        <time>15</time>
        <range>50</range>
        <damage>1</damage>
    </weapon>
    <weapon>
        <name>Laser Grenade</name>
        <type>Grenade</type>
        <type>Throw</type>
        <type>Laser</type>
        <type>Ranged</type>
        <cost>15</cost>
        <passiveEffect>
            <ignoresCover/>
            <wait>25</wait>
            <!--Ignores Cover, target must wait 25 time units on a failed Physical save.-->
        </passiveEffect>
        <difficulty>20</difficulty>
        <time>10</time>
        <range>100</range>
        <damage>0</damage>
    </weapon>
</weapons>

=== ElderNoSpace/Deep-Space-Magic/xml/Equipment/RangedWeapons.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "../Converter.xsl"?> 
<weapons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml.xsd">
    <weapon>
        <name>Ballistic Pistol</name>
        <type>One handed, Ballistic, Pistol, Shoot, Ranged</type>
        <cost>60</cost>
        <passiveEffect></passiveEffect>
        <difficulty>15</difficulty>
        <time>20</time>
        <range>50</range>
        <damage>1</damage>
    </weapon>
    <weapon>
        <name>Laser Pistol</name>
        <type>One handed, Laser, Pistol, Shoot, Ranged</type>
        <cost>85</cost>
        <passiveEffect></passiveEffect>
        <difficulty>15</difficulty>
        <time>15</time>
        <range>25</range>
        <damage>1</damage>
    </weapon>
    <weapon>
        <name>Rail Pistol</name>
        <type>One handed, Rail, Pistol, Shoot, Ranged</type>
        <cost>85</cost>
        <passiveEffect></passiveEffect>
        <difficulty>15</difficulty>
        <time>25</time>
        <range>75</range>
        <damage>1</damage>
    </weapon>
    <weapon>
        <name>Missile Pistol</name>
        <type>One handed, Missile, Pistol, Shoot, Ranged</type>
        <cost>60</cost>
        <passiveEffect></passiveEffect>
        <difficulty>20</difficulty>
        <time>25</time>
        <range>50</range>
        <damage>2</damage>
    </weapon>
    <weapon>
        <name>Plasma Pistol</name>
        <type>One handed, Plasma, Pistol, Shoot, Ranged</type>
        <cost>110</cost>
        <passiveEffect></passiveEffect>
        <difficulty>10</difficulty>
        <time>20</time>
        <range>5</range>
        <aoe>22.5$^{\circ}$ cone</aoe>
        <damage>1</damage>
    </weapon>
    <weapon>
        <name>Ballistic Rifle</name>
        <type>Ballistic, Shoot, Ranged</type>
        <cost>50</cost>
        <difficulty>15</difficulty>
        <time>20</time>
        <range>100</range>
        <damage>1</damage>
    </weapon>
    <weapon>
        <name>Laser Rifle</name>
        <type>Laser, Shoot, Ranged</type>
        <cost>75</cost>
        <difficulty>15</difficulty>
        <time>18</time>
        <range>50</range>
        <damage>1</damage>
    </weapon>
    <weapon>
        <name>Rail Rifle</name>
        <type>Rail Shoot, Ranged</type>
        <cost>75</cost>
        <difficulty>15</difficulty>
        <time>23</time>
        <range>150</range>
        <damage>1</damage>
    </weapon>
    <weapon>
        <name>Missile Gun</name>
        <type>Missile, Shoot, Ranged</type>
        <cost>50</cost>
        <difficulty>20</difficulty>
        <time>25</time>
        <range>100</range>
        <damage>2</damage>
    </weapon>
    <weapon>
        <name>Plasma Gun</name>
        <type>Plasma, Shoot, Ranged</type>
        <cost>100</cost>
        <difficulty>10</difficulty>
        <time>20</time>
        <range>10</range>
        <aoe>45$^{\circ}$ cone</aoe>
        <damage>1</damage>
    </weapon>
    <weapon>
        <name>Light Machine Gun</name>
        <type>Rapid Fire, Ballistic, Shoot, Ranged</type>
        <cost>150</cost>
        <difficulty>15</difficulty>
        <time>15</time>
        <range>75</range>
        <damage>1</damage>
    </weapon>
</weapons>

=== ElderNoSpace/Deep-Space-Magic/xml/Actions/Technomancy.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "../Converter.xsl"?> 
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml.xsd">
    <action upgrade="$l$" difficulty="20" specialist="true">
        <name>Lockdown</name>
        <type>Technomancy</type>
        <type>Hacking</type>
        <type>Mental</type>
        <time>15</time>
        <cost>1 point from the Mental Pool.</cost>
        <effect>For 25 Time Units target Item that is not Simple cannot be used.</effect>
        <upeffect>Difficulty Count is reduced by 1 and duration increases by 25 Time Units per level.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="20" specialist="true">
        <name>Backfire</name>
        <type>Technomancy</type>
        <type>Hacking</type>
        <type>Mental</type>
        <cost>1 point from the Mental Pool.</cost>
        <effect>Target Character with a Weapon that is not Simple equiped within 100m must make a Mental Saving Throw or take 1 damage.</effect>
        <upeffect>Difficultyy Count reduces by 1 per level.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="10" specialist="true">
        <name>Beam Sword Length Liberation</name>
        <type>Technomancy</type>
        <type>Release</type>
        <type>Beam</type>
        <type>Sword</type>
        <type>Melee</type>
        <type>Mental</type>
        <time>10</time>
        <cost>1 point from the Mental Pool.</cost>
        <effect>For 100 Time Units target Beam Sword's Range increases by 1</effect>
        <upeffect>Difficulty count is reduced by 1, the Range increase is increased by 1 and duration increases by 50 Time Units per level.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="10" specialist="true">
        <name>Rapid Fire Release</name>
        <type>Technomancy</type>
        <type>Release</type>
        <type>Rapid Fire</type>
        <type>Mental</type>
        <time>10</time>
        <cost>1 point from the Mental Pool.</cost>
        <effect>Target Shoot Weapon gains Rapid Fire for 100 Time Units</effect>
        <upeffect>Difficulty count is reduced by 1 and duration increases by 50 Time Units per level.</upeffect>
    </action>
    <action upgrade="$l$" difficulty="10" specialist="true">
        <name>Force Distance Extension</name>
        <type>Technomancy</type>
        <type>Release</type>
        <type>Force</type>
        <type>Mental</type>
        <time>10</time>
        <cost>1 point from the Mental Pool.</cost>
        <effect>Target Force Weapon that pushes Characters pushes that Character an extra 1d4m for 100 Time Units.</effect>
        <upeffect>Difficulty count is reduced by 1, roll an extra 1d4 for extra distance and duration increases by 50 Time Units per level.</upeffect>
    </action>
</actions>
